name: MyPlugin
version: 1.0
main: MyPlugin
commands:
  tprequest:
    description: Requests a teleport to user
    aliases:
      - tpr
      - tpreq
    usage: /<command> username
  whispermsg:
    description: whispers a msg to a user
    usage: /<command> message
  sethome:
    description: Sets the users home to the current coordinates
    usage: /<command>
  home:
    description: Teleports the user to their set home
    usage: /<command>